#!/usr/bin/env python
from __future__ import print_function
from bin.main import main

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt as interrupt:
        print (interrupt)